/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Account;

import ChangePassword.ChangePassword;
import Account.Admin;
import Sections.CreateSection;
import Sections.SetSection;
import Sections.StationSection;
import java.awt.Container;
import java.awt.Dimension;



/**
 *
 * @author Eunar B. Dayangco
 */
public class AccountPage extends javax.swing.JFrame {

    /**
     * Creates new form AccountPage
     */
    
    private AccountController controller;
    private ChangePassword changePassword;
    
    
    public AccountPage() {
        initComponents();
        displayAccount();
        accessOption(false);
        this.changePassword = new ChangePassword();
      
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountbodyPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        accountPanel = new javax.swing.JPanel();
        txtAcct_ContactNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAcct_Fullname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAcct_Address = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAcct_Username = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAcct_Email = new javax.swing.JTextField();
        editSavebtn = new javax.swing.JButton();
        changePasswordbtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        accountbodyPanel.setBackground(new java.awt.Color(102, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ACCOUNT INFORMATION");

        accountPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        accountPanel.setOpaque(false);

        txtAcct_ContactNumber.setBackground(new java.awt.Color(153, 0, 0));
        txtAcct_ContactNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAcct_ContactNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtAcct_ContactNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAcct_ContactNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contact Number:");

        txtAcct_Fullname.setBackground(new java.awt.Color(153, 0, 0));
        txtAcct_Fullname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAcct_Fullname.setForeground(new java.awt.Color(255, 255, 255));
        txtAcct_Fullname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAcct_Fullname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fullname:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Address:");

        txtAcct_Address.setBackground(new java.awt.Color(153, 0, 0));
        txtAcct_Address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAcct_Address.setForeground(new java.awt.Color(255, 255, 255));
        txtAcct_Address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAcct_Address.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username:");

        txtAcct_Username.setBackground(new java.awt.Color(153, 0, 0));
        txtAcct_Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAcct_Username.setForeground(new java.awt.Color(255, 255, 255));
        txtAcct_Username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAcct_Username.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email:");

        txtAcct_Email.setBackground(new java.awt.Color(153, 0, 0));
        txtAcct_Email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAcct_Email.setForeground(new java.awt.Color(255, 255, 255));
        txtAcct_Email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAcct_Email.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAcct_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAcct_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(accountPanelLayout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addComponent(txtAcct_Fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(accountPanelLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addComponent(txtAcct_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(accountPanelLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(20, 20, 20)
                            .addComponent(txtAcct_ContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(txtAcct_Fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(txtAcct_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addComponent(txtAcct_ContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAcct_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addComponent(txtAcct_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        editSavebtn.setBackground(new java.awt.Color(153, 0, 0));
        editSavebtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        editSavebtn.setForeground(new java.awt.Color(255, 255, 255));
        editSavebtn.setText("EDIT");
        editSavebtn.setFocusPainted(false);
        editSavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSavebtnActionPerformed(evt);
            }
        });

        changePasswordbtn.setBackground(new java.awt.Color(153, 0, 0));
        changePasswordbtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        changePasswordbtn.setForeground(new java.awt.Color(255, 255, 255));
        changePasswordbtn.setText("CHANGE PASSWORD");
        changePasswordbtn.setFocusPainted(false);
        changePasswordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordbtnActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SHOW LOGGED");
        jButton3.setFocusPainted(false);

        javax.swing.GroupLayout accountbodyPanelLayout = new javax.swing.GroupLayout(accountbodyPanel);
        accountbodyPanel.setLayout(accountbodyPanelLayout);
        accountbodyPanelLayout.setHorizontalGroup(
            accountbodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountbodyPanelLayout.createSequentialGroup()
                .addGroup(accountbodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountbodyPanelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(accountbodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(accountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(accountbodyPanelLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(41, 41, 41)
                                .addComponent(editSavebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(changePasswordbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountbodyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        accountbodyPanelLayout.setVerticalGroup(
            accountbodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountbodyPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(accountbodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(accountbodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editSavebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(changePasswordbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountbodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountbodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editSavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSavebtnActionPerformed
        String label = editSavebtn.getText();
        
        if(label.equals("EDIT")){
            editSavebtn.setText("SAVE");
            accessOption(true);
        }else{
            
            setUpdate();
            editSavebtn.setText("EDIT");
            accessOption(false);
        }
    }//GEN-LAST:event_editSavebtnActionPerformed

    private void changePasswordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordbtnActionPerformed
       
        
        new SetSection().setDisplayFromDown(this.changePassword, 70);

    }//GEN-LAST:event_changePasswordbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountPanel;
    private javax.swing.JPanel accountbodyPanel;
    private javax.swing.JButton changePasswordbtn;
    private javax.swing.JButton editSavebtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAcct_Address;
    private javax.swing.JTextField txtAcct_ContactNumber;
    private javax.swing.JTextField txtAcct_Email;
    private javax.swing.JTextField txtAcct_Fullname;
    private javax.swing.JTextField txtAcct_Username;
    // End of variables declaration//GEN-END:variables

    public void displayAccount(){
        
        Admin myAccount = StationSection.getLoggedAdmin();
        
        txtAcct_Fullname.setText(myAccount.getAdminFullname());
        txtAcct_Address.setText(myAccount.getAdminAddress());
        txtAcct_ContactNumber.setText(myAccount.getAdminContactNumber());
        txtAcct_Username.setText(myAccount.getAdminUsername());
        txtAcct_Email.setText(myAccount.getAdminEmail());
    
    }
    public void accessOption(boolean access){
        
        txtAcct_Fullname.setEnabled(access);
        txtAcct_Address.setEnabled(access);
        txtAcct_ContactNumber.setEnabled(access);
        txtAcct_Username.setEnabled(access);
        txtAcct_Email.setEnabled(access);
    
    }
    public void setUpdate(){
        
        Admin updatedAdmin = StationSection.getLoggedAdmin();
        updatedAdmin.setAdminFullname(txtAcct_Fullname.getText());
        updatedAdmin.setAdminAddress(txtAcct_Address.getText());
        updatedAdmin.setAdminContactNumber(txtAcct_ContactNumber.getText());
        updatedAdmin.setAdminUsername(txtAcct_Username.getText());
        updatedAdmin.setAdminEmail(txtAcct_Email.getText());
        controller = new AccountController(updatedAdmin);
        controller.editAccount();
        
        if(controller.isSuccess()){
            CreateSection.displayInfoMessage("Account Edit Information", "Successfully Edit Your Account");
            StationSection.setLoggedAdmin(updatedAdmin);
            displayAccount();
        }else{
             CreateSection.displayErrorMessage("Account Edit Error", "Sorry! cannot edit your account.");
        }
    
    }

   
    
}

