/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Employee;

import Controller.EmployeeController;
import Model.Employee;
import Sections.SetSection;
import Views.Slider.AnimationSection;
import java.awt.Color;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Eunar B. Dayangco
 */
public class EditEmployee extends javax.swing.JFrame {

    /**
     * Creates new form EditEmployee
     */
    private EmployeeController controller;
    public EditEmployee() {
        initComponents();
        designComponents();
        init();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeListTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEmployeeName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmployeePos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmployeeEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmployeeNumber = new javax.swing.JTextField();
        newbtn1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        closebtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(null);

        mainPanel.setBackground(new java.awt.Color(161, 214, 226));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.setLayout(null);

        employeeListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmployeeID", "Name", "Position"
            }
        ));
        jScrollPane1.setViewportView(employeeListTable);
        if (employeeListTable.getColumnModel().getColumnCount() > 0) {
            employeeListTable.getColumnModel().getColumn(0).setResizable(false);
        }

        mainPanel.add(jScrollPane1);
        jScrollPane1.setBounds(410, 90, 400, 460);

        jPanel2.setBackground(new java.awt.Color(25, 149, 173));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Employee Name:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 30, 152, 22);

        txtEmployeeName.setBackground(new java.awt.Color(161, 214, 226));
        txtEmployeeName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmployeeName.setAlignmentX(1.0F);
        txtEmployeeName.setAlignmentY(3.0F);
        txtEmployeeName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(txtEmployeeName);
        txtEmployeeName.setBounds(40, 70, 275, 36);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Employee Position:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 120, 171, 22);

        txtEmployeePos.setBackground(new java.awt.Color(161, 214, 226));
        txtEmployeePos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmployeePos.setAlignmentX(1.0F);
        txtEmployeePos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(txtEmployeePos);
        txtEmployeePos.setBounds(40, 150, 275, 36);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Employee Email:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 210, 148, 22);

        txtEmployeeEmail.setBackground(new java.awt.Color(161, 214, 226));
        txtEmployeeEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmployeeEmail.setAlignmentX(1.0F);
        txtEmployeeEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(txtEmployeeEmail);
        txtEmployeeEmail.setBounds(40, 240, 275, 36);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Contact Number:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 290, 155, 22);

        txtEmployeeNumber.setBackground(new java.awt.Color(161, 214, 226));
        txtEmployeeNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmployeeNumber.setAlignmentX(1.0F);
        txtEmployeeNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(txtEmployeeNumber);
        txtEmployeeNumber.setBounds(40, 330, 275, 36);

        newbtn1.setBackground(new java.awt.Color(25, 149, 173));
        newbtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newbtn1.setText("SAVE");
        newbtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        newbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(newbtn1);
        newbtn1.setBounds(210, 390, 103, 40);

        mainPanel.add(jPanel2);
        jPanel2.setBounds(30, 90, 360, 460);

        jPanel3.setBackground(new java.awt.Color(25, 149, 173));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/xbutton.png"))); // NOI18N
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        jPanel3.add(closebtn);
        closebtn.setBounds(810, 0, 50, 40);

        mainPanel.add(jPanel3);
        jPanel3.setBounds(0, 0, 860, 40);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, 860, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newbtn1ActionPerformed

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        new AnimationSection().framesMoveBacktoTop(this, 70, 20);
    }//GEN-LAST:event_closebtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closebtn;
    private javax.swing.JTable employeeListTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton newbtn1;
    private javax.swing.JTextField txtEmployeeEmail;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JTextField txtEmployeeNumber;
    private javax.swing.JTextField txtEmployeePos;
    // End of variables declaration//GEN-END:variables

    private void designComponents() {
        this.setBackground(new Color(0,0,0,0));
        new SetSection().designForm(this, mainPanel, "mini");
        
        
    }
    public void init(){
        
        this.controller = new EmployeeController();
        this.controller.displayOnEditEmployeesTable(employeeListTable);
        
         employeeListTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
           

            @Override
            public void valueChanged(ListSelectionEvent e) {
                 if(!employeeListTable.getSelectionModel().isSelectionEmpty()){
                    int row = employeeListTable.getSelectedRow();
                    int employeeID = Integer.parseInt(employeeListTable.getValueAt(row, 0).toString());
                    Employee employee = new EmployeeController().getEmployee(employeeID);
                     displayData(employee);
                    
                }
            }
        });
    
    }
    
    public void displayData(Employee employee){
        txtEmployeeName.setText(employee.getFullname());
        txtEmployeePos.setText(employee.getPosition());
        txtEmployeeEmail.setText(employee.getEmail());
        txtEmployeeNumber.setText(employee.getContactNumber());
        
    }
    
  
}
