/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Employee;



import Controller.EmployeeController;

import Model.Employee;
import Sections.CreateSection;
import Sections.SetSection;
import Sections.StationSection;
import java.util.ArrayList;
import java.util.Collections;


/**
 *
 * @author Eunar B. Dayangco
 */
public class EmployeeUI extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeSearch
     */
   
    private EmployeeController controller;
    private EditEmployee editEmployee;
  
    public EmployeeUI() {
        initComponents();
     
        this.controller = new EmployeeController();
        this.editEmployee = new EditEmployee();
        new SetSection().designForm(this, mainPanel, "mini");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEmployeeName = new javax.swing.JTextField();
        txtEmployeePos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        newbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtEmployeeNumber = new javax.swing.JTextField();
        txtEmployeeEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        newbtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        mainPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Employee Name:");
        mainPanel.add(jLabel1);
        jLabel1.setBounds(40, 70, 152, 22);

        txtEmployeeName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmployeeName.setAlignmentX(1.0F);
        txtEmployeeName.setAlignmentY(3.0F);
        txtEmployeeName.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        mainPanel.add(txtEmployeeName);
        txtEmployeeName.setBounds(40, 110, 275, 36);

        txtEmployeePos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmployeePos.setAlignmentX(1.0F);
        txtEmployeePos.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        mainPanel.add(txtEmployeePos);
        txtEmployeePos.setBounds(40, 190, 275, 36);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Employee Position:");
        mainPanel.add(jLabel3);
        jLabel3.setBounds(40, 160, 171, 22);

        newbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newbtn.setText("EDIT");
        newbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbtnActionPerformed(evt);
            }
        });
        mainPanel.add(newbtn);
        newbtn.setBounds(40, 440, 103, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Contact Number:");
        mainPanel.add(jLabel4);
        jLabel4.setBounds(40, 330, 155, 22);

        txtEmployeeNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmployeeNumber.setAlignmentX(1.0F);
        txtEmployeeNumber.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        mainPanel.add(txtEmployeeNumber);
        txtEmployeeNumber.setBounds(40, 370, 275, 36);

        txtEmployeeEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmployeeEmail.setAlignmentX(1.0F);
        txtEmployeeEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        mainPanel.add(txtEmployeeEmail);
        txtEmployeeEmail.setBounds(40, 280, 275, 36);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Employee Email:");
        mainPanel.add(jLabel5);
        jLabel5.setBounds(40, 250, 148, 22);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 0, 3, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/xbutton.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 0, 50, 40);

        mainPanel.add(jPanel1);
        jPanel1.setBounds(0, 0, 350, 40);

        newbtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newbtn1.setText("ADD");
        newbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbtn1ActionPerformed(evt);
            }
        });
        mainPanel.add(newbtn1);
        newbtn1.setBounds(210, 440, 103, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbtnActionPerformed
        
        
        
    }//GEN-LAST:event_newbtnActionPerformed

    private void newbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton newbtn;
    private javax.swing.JButton newbtn1;
    private javax.swing.JTextField txtEmployeeEmail;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JTextField txtEmployeeNumber;
    private javax.swing.JTextField txtEmployeePos;
    // End of variables declaration//GEN-END:variables

   
    
    public void clearAll(){
        
        txtEmployeeName.setText("");
        txtEmployeePos.setText("");
        txtEmployeeNumber.setText("");
    }
    


}
