/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Inventory;



import Controller.EmployeeController;
import Controller.LocationController;
import Model.Employee;
import Model.Inventory;
import Model.Location;
import Sections.CreateSection;
import Sections.SetSection;
import Views.Inventory.ShootImage;
import Views.Slider.AnimationSection;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;


/**
 *
 * @author Eunar B. Dayangco
 */
public class InventoryInfo extends javax.swing.JFrame {

    
    private final Inventory inventory;
    public int xMouse,yMouse;
    private ArrayList<Employee> employees;
    private ArrayList<Location> locations;
    private ScanInventory scanned;
    
    
    public InventoryInfo() {
        initComponents();
        inventory = new Inventory();
        init();
    }
    
    public InventoryInfo(Inventory inventory) {
        initComponents();
        this.inventory = inventory;
        init();
    }
    
    public InventoryInfo(Inventory inventory,ScanInventory scanned) {
        initComponents();
        this.inventory = inventory;
        this.scanned = scanned;
        init();
    }
    
    public void init(){
        
      new SetSection().designForm(this, bodyPanel, "mini");
      displayEmployees();
      displayLocations();
      displayInformation();
      
      
        
    }
    
 
    
    public void accessStatus(boolean status){
        
        txtinventoryName.setEnabled(status);
        txtIssuedBy.setEnabled(status);
        findIssuedbutton.setEnabled(status);
        txtReceivedBy.setEnabled(status);
        findReceivedbtn.setEnabled(status);
        txtSnNumber.setEnabled(status);
        txtAmount.setEnabled(status);
        txtStatus.setEnabled(status);
        cbinventoryLocation.setEnabled(status);
        findLocationbtn.setEnabled(status);
        txtDescription.setEnabled(status);
        txtRemarks.setEnabled(status);
        uploadbtn.setEnabled(status);
        shootImage.setEnabled(status);
     
        setDisabledColor(Color.BLACK);
     
   
    }
    
    public void setDisabledColor(Color color){
        
        txtinventoryName.setDisabledTextColor(color);
        txtSnNumber.setDisabledTextColor(color);
        txtAmount.setDisabledTextColor(color);
        txtDescription.setDisabledTextColor(color);
        txtRemarks.setDisabledTextColor(color);
        UIManager.put("ComboBox.disabledForeground", color);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        displayImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_parNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtinventoryName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIssuedBy = new javax.swing.JComboBox<>();
        findIssuedbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtReceivedBy = new javax.swing.JComboBox<>();
        findReceivedbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSnNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtRemarks = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        uploadbtn = new javax.swing.JButton();
        shootImage = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cbinventoryLocation = new javax.swing.JComboBox<>();
        findLocationbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        editSavebtn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        headbar = new javax.swing.JPanel();
        txtID = new javax.swing.JLabel();
        minbtn = new javax.swing.JLabel();
        closebtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        bodyPanel.setBackground(new java.awt.Color(0, 153, 0));
        bodyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bodyPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bodyPanelMouseDragged(evt);
            }
        });
        bodyPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bodyPanelMousePressed(evt);
            }
        });
        bodyPanel.setLayout(null);

        displayImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bodyPanel.add(displayImage);
        displayImage.setBounds(40, 50, 250, 220);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("PAR no.:");
        bodyPanel.add(jLabel2);
        jLabel2.setBounds(340, 50, 78, 22);

        txt_parNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_parNo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_parNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_parNoKeyTyped(evt);
            }
        });
        bodyPanel.add(txt_parNo);
        txt_parNo.setBounds(440, 50, 328, 26);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("    Name:");
        bodyPanel.add(jLabel6);
        jLabel6.setBounds(340, 90, 90, 22);

        txtinventoryName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtinventoryName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bodyPanel.add(txtinventoryName);
        txtinventoryName.setBounds(440, 90, 328, 26);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Issued by: ");
        bodyPanel.add(jLabel3);
        jLabel3.setBounds(330, 130, 99, 22);

        txtIssuedBy.setEditable(true);
        txtIssuedBy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bodyPanel.add(txtIssuedBy);
        txtIssuedBy.setBounds(440, 130, 260, 31);

        findIssuedbutton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        findIssuedbutton.setText("...");
        findIssuedbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findIssuedbuttonActionPerformed(evt);
            }
        });
        bodyPanel.add(findIssuedbutton);
        findIssuedbutton.setBounds(710, 130, 60, 28);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Received by: ");
        bodyPanel.add(jLabel4);
        jLabel4.setBounds(310, 170, 120, 22);

        txtReceivedBy.setEditable(true);
        txtReceivedBy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bodyPanel.add(txtReceivedBy);
        txtReceivedBy.setBounds(440, 170, 260, 31);

        findReceivedbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        findReceivedbtn.setText("...");
        findReceivedbtn.setToolTipText("");
        findReceivedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findReceivedbtnActionPerformed(evt);
            }
        });
        bodyPanel.add(findReceivedbtn);
        findReceivedbtn.setBounds(710, 170, 60, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText(" SN Number:");
        bodyPanel.add(jLabel5);
        jLabel5.setBounds(310, 210, 120, 22);

        txtSnNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSnNumber.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bodyPanel.add(txtSnNumber);
        txtSnNumber.setBounds(440, 210, 330, 26);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Amount:");
        bodyPanel.add(jLabel8);
        jLabel8.setBounds(350, 250, 78, 22);

        txtAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bodyPanel.add(txtAmount);
        txtAmount.setBounds(440, 250, 330, 26);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Description:");
        bodyPanel.add(jLabel10);
        jLabel10.setBounds(40, 380, 110, 22);

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        bodyPanel.add(jScrollPane1);
        jScrollPane1.setBounds(40, 410, 410, 100);

        txtRemarks.setColumns(20);
        txtRemarks.setRows(5);
        jScrollPane3.setViewportView(txtRemarks);

        bodyPanel.add(jScrollPane3);
        jScrollPane3.setBounds(470, 410, 300, 100);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("  Remarks:");
        bodyPanel.add(jLabel7);
        jLabel7.setBounds(460, 380, 110, 22);

        uploadbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uploadbtn.setText("Upload Image");
        uploadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadbtnActionPerformed(evt);
            }
        });
        bodyPanel.add(uploadbtn);
        uploadbtn.setBounds(40, 290, 250, 30);

        shootImage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        shootImage.setText("Shoot Image");
        shootImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shootImageActionPerformed(evt);
            }
        });
        bodyPanel.add(shootImage);
        shootImage.setBounds(40, 330, 250, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" Location:");
        bodyPanel.add(jLabel11);
        jLabel11.setBounds(340, 330, 90, 22);

        cbinventoryLocation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbinventoryLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DICT Office" }));
        bodyPanel.add(cbinventoryLocation);
        cbinventoryLocation.setBounds(440, 330, 270, 30);

        findLocationbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        findLocationbtn.setText("...");
        bodyPanel.add(findLocationbtn);
        findLocationbtn.setBounds(720, 330, 50, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText(" Status:");
        bodyPanel.add(jLabel9);
        jLabel9.setBounds(360, 290, 70, 22);

        txtStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Serviceable", "Unserviceable", " " }));
        bodyPanel.add(txtStatus);
        txtStatus.setBounds(440, 290, 330, 31);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("UPDATE INFO");
        bodyPanel.add(jButton3);
        jButton3.setBounds(240, 530, 210, 40);

        editSavebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        editSavebtn.setText("EDIT");
        editSavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSavebtnActionPerformed(evt);
            }
        });
        bodyPanel.add(editSavebtn);
        editSavebtn.setBounds(630, 530, 140, 40);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("PRINT ");
        bodyPanel.add(jButton6);
        jButton6.setBounds(470, 530, 140, 40);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("GENERATE ");
        bodyPanel.add(jButton7);
        jButton7.setBounds(40, 530, 180, 40);

        headbar.setBackground(new java.awt.Color(0, 0, 102));
        headbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        headbar.setLayout(null);

        txtID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setText("ID here");
        headbar.add(txtID);
        txtID.setBounds(30, 4, 210, 20);

        minbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/headers/minimize.png"))); // NOI18N
        minbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minbtnMouseClicked(evt);
            }
        });
        headbar.add(minbtn);
        minbtn.setBounds(750, 0, 30, 30);

        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/headers/cancel.png"))); // NOI18N
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        headbar.add(closebtn);
        closebtn.setBounds(780, 0, 30, 30);

        bodyPanel.add(headbar);
        headbar.setBounds(0, 0, 810, 30);

        getContentPane().add(bodyPanel);
        bodyPanel.setBounds(0, 0, 810, 590);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bodyPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bodyPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_bodyPanelMouseDragged

    private void bodyPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bodyPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_bodyPanelMousePressed

    private void txt_parNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_parNoKeyTyped
      


    }//GEN-LAST:event_txt_parNoKeyTyped

    private void findIssuedbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findIssuedbuttonActionPerformed

       /* StationSection.setCreateInventoryOpened(this);
        this.setEnabled(false);
        new CreateEmployee().setVisible(true);*/
    }//GEN-LAST:event_findIssuedbuttonActionPerformed

    private void findReceivedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findReceivedbtnActionPerformed

       /* StationSection.setCreateInventoryOpened(this);
        this.setEnabled(false);
        new CreateEmployee().setVisible(true);*/
    }//GEN-LAST:event_findReceivedbtnActionPerformed

    private void uploadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadbtnActionPerformed

       // emptyImages();
        //findImage();
    }//GEN-LAST:event_uploadbtnActionPerformed

    private void shootImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shootImageActionPerformed
        // TODO add your handling code here:
       // emptyImages();
        new ShootImage().setVisible(true);
    }//GEN-LAST:event_shootImageActionPerformed

    private void editSavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSavebtnActionPerformed
       
    }//GEN-LAST:event_editSavebtnActionPerformed

    private void minbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minbtnMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minbtnMouseClicked

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        this.scanned.setResultFound("");
        new AnimationSection().framesMoveBacktoTop(this, 70, 35);
        

    }//GEN-LAST:event_closebtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JComboBox<String> cbinventoryLocation;
    private javax.swing.JLabel closebtn;
    private javax.swing.JLabel displayImage;
    private javax.swing.JButton editSavebtn;
    private javax.swing.JButton findIssuedbutton;
    private javax.swing.JButton findLocationbtn;
    private javax.swing.JButton findReceivedbtn;
    private javax.swing.JPanel headbar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel minbtn;
    private javax.swing.JButton shootImage;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JLabel txtID;
    private javax.swing.JComboBox<String> txtIssuedBy;
    private javax.swing.JComboBox<String> txtReceivedBy;
    private javax.swing.JTextArea txtRemarks;
    private javax.swing.JTextField txtSnNumber;
    private javax.swing.JComboBox<String> txtStatus;
    private javax.swing.JTextField txt_parNo;
    private javax.swing.JTextField txtinventoryName;
    private javax.swing.JButton uploadbtn;
    // End of variables declaration//GEN-END:variables
    
    
    public void displayInformation(){
        
        
        txt_parNo.setText(this.inventory.getInventoryPAR_NO());
        txtinventoryName.setText(this.inventory.getInventoryName());
        txtIssuedBy.setSelectedItem(this.inventory.getIssuedBy().getFullname());
        txtReceivedBy.setSelectedItem(this.inventory.getReceivedBy().getFullname());
        txtSnNumber.setText(this.inventory.getInventorySN());
        txtAmount.setText(this.inventory.getInventoryAmount()+"");
        txtStatus.setSelectedItem(this.inventory.getInventoryStatus());
        cbinventoryLocation.setSelectedItem(this.inventory.getInventoryLocation().getAddress());
        txtDescription.setText(this.inventory.getInventoryDescription());
        txtRemarks.setText(this.inventory.getInventoryRemarks());
        displayImage();
        
    }
    
    public void displayImage(){
        try{
        
            displayImage.setIcon(null);
           
            Image resizedImage = this.inventory.getInventoryImage().getScaledInstance(displayImage.getWidth(), displayImage.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon newImage = new ImageIcon(resizedImage);
            displayImage.setIcon(newImage);
            
        
        }catch(NullPointerException ex){
            CreateSection.displayInfoMessage("Display Image on JLabel error.", ex.toString());
        }
    }
    
    public void displayEmployees(){
        
         this.employees = new EmployeeController().getAllEmployees();
        
        
         txtIssuedBy.removeAllItems();
        
        for(Employee employee:this.employees){
            
            txtIssuedBy.addItem(employee.getFullname());
        }
    }
    
    public void displayLocations(){
        
        this.locations = new LocationController().getAllLocations();
          cbinventoryLocation.removeAllItems();
        
        for(Location location:this.locations){
            
            cbinventoryLocation.addItem(location.getAddress());
        }
    }
    
    
    
    
    
   
}
