/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import Sections.CreateSection;
import Sections.SendEmail;
import Sections.SetSection;

/**
 *
 * @author Eunar B. Dayangco
 */
public class EditUser extends javax.swing.JFrame {

    /**
     * Creates new form EditUser
     */
    private UserController controller;
    private User user;

    
    public EditUser() {
        initComponents();
        new SetSection().designForm(this, editMainPanel, "mini");
        this.controller = new UserController();
        this.user = new User();
        
    }
    
    public EditUser(User user){
        
        initComponents();
        this.user = user;
        this.controller = new UserController();
        manualize();
    }
    
    public void manualize(){
     new SetSection().designForm(this, editMainPanel, "mini");
             displayInfo();
        accessOption(false);
        txtEditPassword.setEchoChar('*');
    
    }
    
    public void displayInfo(){
        
        txtEditFullname.setText(user.getUserFullname());
        txtEditPosition.setText(user.getUserPosition());
        txtEditContactNumber.setText(user.getUserContactNumber());
        txtEditEmail.setText(user.getUserEmail());
        txtEditUsername.setText(user.getUserUsername());
        txtEditPassword.setText(user.getUserPassword());
        
    }
    
    public void accessOption(boolean stat){
        txtEditFullname.setEnabled(stat);
        txtEditPosition.setEnabled(stat);
        txtEditContactNumber.setEnabled(stat);
        txtEditEmail.setEnabled(stat);
        txtEditUsername.setEnabled(stat);
        txtEditPassword.setEnabled(stat);
    }
    
    public User editedUser(){
    
        User editUser= this.user;
        editUser.setUserFullname(txtEditFullname.getText());
        editUser.setUserPosition(txtEditPosition.getText());
        editUser.setUserContactNumber(txtEditContactNumber.getText());
        editUser.setUserEmail(txtEditEmail.getText());
        editUser.setUserUsername(txtEditUsername.getText());
        editUser.setUserPassword(txtEditPassword.getText());        
        return editUser;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editMainPanel = new javax.swing.JPanel();
        headbar = new javax.swing.JPanel();
        closebtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEditFullname = new javax.swing.JTextField();
        txtEditPosition = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEditEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEditContactNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEditUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sendEmailbtn = new javax.swing.JButton();
        sendEmailbtn1 = new javax.swing.JButton();
        showHidecb = new javax.swing.JCheckBox();
        txtEditPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        editMainPanel.setBackground(new java.awt.Color(0, 0, 255));
        editMainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        editMainPanel.setLayout(null);

        headbar.setBackground(new java.awt.Color(0, 0, 0));
        headbar.setLayout(null);

        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/LoginComponents/cancel.png"))); // NOI18N
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        headbar.add(closebtn);
        closebtn.setBounds(590, 0, 30, 30);

        editMainPanel.add(headbar);
        headbar.setBounds(0, 0, 620, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fullname:");
        editMainPanel.add(jLabel1);
        jLabel1.setBounds(40, 70, 90, 30);

        txtEditFullname.setBackground(new java.awt.Color(0, 0, 102));
        txtEditFullname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEditFullname.setForeground(new java.awt.Color(255, 255, 255));
        txtEditFullname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEditFullname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        editMainPanel.add(txtEditFullname);
        txtEditFullname.setBounds(210, 70, 330, 30);

        txtEditPosition.setBackground(new java.awt.Color(0, 0, 102));
        txtEditPosition.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEditPosition.setForeground(new java.awt.Color(255, 255, 255));
        txtEditPosition.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEditPosition.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        editMainPanel.add(txtEditPosition);
        txtEditPosition.setBounds(210, 110, 330, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Position:");
        editMainPanel.add(jLabel2);
        jLabel2.setBounds(40, 110, 90, 30);

        txtEditEmail.setBackground(new java.awt.Color(0, 0, 102));
        txtEditEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEditEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEditEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEditEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        editMainPanel.add(txtEditEmail);
        txtEditEmail.setBounds(210, 150, 330, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        editMainPanel.add(jLabel3);
        jLabel3.setBounds(40, 150, 90, 30);

        txtEditContactNumber.setBackground(new java.awt.Color(0, 0, 102));
        txtEditContactNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEditContactNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtEditContactNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEditContactNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        editMainPanel.add(txtEditContactNumber);
        txtEditContactNumber.setBounds(210, 190, 330, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact Number:");
        editMainPanel.add(jLabel4);
        jLabel4.setBounds(40, 190, 160, 30);

        txtEditUsername.setBackground(new java.awt.Color(0, 0, 102));
        txtEditUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEditUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtEditUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEditUsername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        editMainPanel.add(txtEditUsername);
        txtEditUsername.setBounds(210, 230, 330, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username:");
        editMainPanel.add(jLabel5);
        jLabel5.setBounds(40, 230, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password:");
        editMainPanel.add(jLabel6);
        jLabel6.setBounds(40, 270, 110, 30);

        sendEmailbtn.setBackground(new java.awt.Color(204, 0, 0));
        sendEmailbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sendEmailbtn.setForeground(new java.awt.Color(255, 255, 255));
        sendEmailbtn.setText("Edit");
        sendEmailbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sendEmailbtn.setFocusPainted(false);
        sendEmailbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEmailbtnActionPerformed(evt);
            }
        });
        sendEmailbtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sendEmailbtnKeyPressed(evt);
            }
        });
        editMainPanel.add(sendEmailbtn);
        sendEmailbtn.setBounds(430, 320, 110, 40);

        sendEmailbtn1.setBackground(new java.awt.Color(204, 0, 0));
        sendEmailbtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sendEmailbtn1.setForeground(new java.awt.Color(255, 255, 255));
        sendEmailbtn1.setText("Send to Email");
        sendEmailbtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sendEmailbtn1.setFocusPainted(false);
        sendEmailbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEmailbtn1ActionPerformed(evt);
            }
        });
        sendEmailbtn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sendEmailbtn1KeyPressed(evt);
            }
        });
        editMainPanel.add(sendEmailbtn1);
        sendEmailbtn1.setBounds(210, 320, 160, 40);

        showHidecb.setBackground(new java.awt.Color(0, 0, 255));
        showHidecb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        showHidecb.setForeground(new java.awt.Color(255, 255, 255));
        showHidecb.setText("SHOW");
        showHidecb.setOpaque(false);
        showHidecb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showHidecbItemStateChanged(evt);
            }
        });
        editMainPanel.add(showHidecb);
        showHidecb.setBounds(480, 270, 90, 30);

        txtEditPassword.setBackground(new java.awt.Color(0, 0, 102));
        txtEditPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEditPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtEditPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEditPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtEditPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEditPasswordKeyPressed(evt);
            }
        });
        editMainPanel.add(txtEditPassword);
        txtEditPassword.setBounds(210, 270, 270, 30);

        getContentPane().add(editMainPanel);
        editMainPanel.setBounds(0, 0, 620, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked

        this.setVisible(false);
    }//GEN-LAST:event_closebtnMouseClicked

    private void sendEmailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEmailbtnActionPerformed
        String label = sendEmailbtn.getText();
        
        if(label.equals("Edit")){
            accessOption(true);
            sendEmailbtn.setText("Save");
        }else{
            
            controller = new UserController(editedUser());
            
             
            controller.updateUser();
            
            if(controller.isSuccess()){
                
                CreateSection.displayInfoMessage("Confirmation", 
                        "Successfully Edit User!");
                
                sendEmailbtn.setText("Edit");
                accessOption(false);
                new SetSection().setDisplayFromAbove(this, 70);
                
                
            }else{
                 CreateSection.displayErrorMessage("Edit User Error",
                         "Cannot Edit User!");
            }
            
           
            
        }
     

    }//GEN-LAST:event_sendEmailbtnActionPerformed

    private void sendEmailbtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sendEmailbtnKeyPressed

    }//GEN-LAST:event_sendEmailbtnKeyPressed

    private void sendEmailbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEmailbtn1ActionPerformed
      
        SendEmail emailsender = new SendEmail();
        String username = "Your username is " + this.user.getUserUsername();
        String password = "Your password is " + this.user.getUserPassword();
        String messages = username+" and "+ password;
        
        if(emailsender.sendMailWithAttachedMent(txtEditEmail.getText(), "Supply Office Account Information", messages)){
           
          
            CreateSection.displayInfoMessage("Confirmation", "Email send successfully");
        }
        
    }//GEN-LAST:event_sendEmailbtn1ActionPerformed

    private void sendEmailbtn1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sendEmailbtn1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendEmailbtn1KeyPressed

    private void showHidecbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showHidecbItemStateChanged
            boolean checked = showHidecb.isSelected();
            
            if(checked){
                 txtEditPassword.setEchoChar((char)0);
                showHidecb.setText("HIDE");
            }else{
                txtEditPassword.setEchoChar('*');
                showHidecb.setText("SHOW");
               
            }
            
    }//GEN-LAST:event_showHidecbItemStateChanged

    private void txtEditPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditPasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closebtn;
    private javax.swing.JPanel editMainPanel;
    private javax.swing.JPanel headbar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton sendEmailbtn;
    private javax.swing.JButton sendEmailbtn1;
    private javax.swing.JCheckBox showHidecb;
    private javax.swing.JTextField txtEditContactNumber;
    private javax.swing.JTextField txtEditEmail;
    private javax.swing.JTextField txtEditFullname;
    private javax.swing.JPasswordField txtEditPassword;
    private javax.swing.JTextField txtEditPosition;
    private javax.swing.JTextField txtEditUsername;
    // End of variables declaration//GEN-END:variables
}
