/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Location;

import Sections.SetSection;
import Views.Slider.AnimationSection;
import java.awt.Color;

/**
 *
 * @author Eunar B. Dayangco
 */
public class EditLocation extends javax.swing.JFrame {

    /**
     * Creates new form EditLocation
     */
    public EditLocation() {
        initComponents();
        desigComponents();
    }
    
    public void desigComponents(){
        new SetSection().designForm(this, bodyPanel, "mini");
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        closebtn = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtLocationAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtlocationContactNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLocationDescription = new javax.swing.JTextArea();
        savebtn = new javax.swing.JButton();
        txtLocationContactPerson = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(null);

        bodyPanel.setBackground(new java.awt.Color(161, 214, 226));
        bodyPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bodyPanel.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(25, 149, 173));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/xbutton.png"))); // NOI18N
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        jPanel2.add(closebtn);
        closebtn.setBounds(890, 0, 40, 40);

        bodyPanel.add(jPanel2);
        jPanel2.setBounds(0, 0, 930, 40);

        mainPanel.setBackground(new java.awt.Color(161, 214, 226));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Location:");
        mainPanel.add(jLabel3);
        jLabel3.setBounds(40, 30, 64, 17);

        txtLocationAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mainPanel.add(txtLocationAddress);
        txtLocationAddress.setBounds(40, 50, 330, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Contact Number:");
        mainPanel.add(jLabel4);
        jLabel4.setBounds(40, 110, 120, 17);

        txtlocationContactNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mainPanel.add(txtlocationContactNumber);
        txtlocationContactNumber.setBounds(40, 130, 330, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Contact Person:");
        mainPanel.add(jLabel5);
        jLabel5.setBounds(40, 190, 112, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Description:");
        mainPanel.add(jLabel6);
        jLabel6.setBounds(40, 260, 82, 17);

        txtLocationDescription.setColumns(20);
        txtLocationDescription.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtLocationDescription.setRows(5);
        jScrollPane1.setViewportView(txtLocationDescription);

        mainPanel.add(jScrollPane1);
        jScrollPane1.setBounds(40, 290, 330, 72);

        savebtn.setBackground(new java.awt.Color(0, 0, 102));
        savebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        savebtn.setForeground(new java.awt.Color(255, 255, 255));
        savebtn.setText("SAVE");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        mainPanel.add(savebtn);
        savebtn.setBounds(250, 380, 120, 40);

        txtLocationContactPerson.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mainPanel.add(txtLocationContactPerson);
        txtLocationContactPerson.setBounds(40, 210, 330, 40);

        bodyPanel.add(mainPanel);
        mainPanel.setBounds(40, 70, 410, 450);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Contact Number"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        bodyPanel.add(jScrollPane2);
        jScrollPane2.setBounds(460, 70, 430, 450);

        getContentPane().add(bodyPanel);
        bodyPanel.setBounds(0, 0, 930, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed

    }//GEN-LAST:event_savebtnActionPerformed

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
          new AnimationSection().framesMoveBacktoTop(this, 70, 20);
    }//GEN-LAST:event_closebtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditLocation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel closebtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField txtLocationAddress;
    private javax.swing.JTextField txtLocationContactPerson;
    private javax.swing.JTextArea txtLocationDescription;
    private javax.swing.JTextField txtlocationContactNumber;
    // End of variables declaration//GEN-END:variables
}
