/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Location;

import Model.Location;
import Controller.LocationController;
import Database.LocationDB;
import Views.Employee.EmployeeUI;
import Sections.CreateSection;
import Sections.SetSection;
import Sections.StationSection;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Collections;



/**
 *
 * @author Eunar B. Dayangco
 */
public class LocationUI extends javax.swing.JFrame {

    /**
     * Creates new form LocationUI
     */
    
    public int xMouse, yMouse;
    private LocationController controller;
    private ArrayList <Location> locations;
    
    public LocationUI() {
        initComponents();
        init();
    }
    
    
    public void init(){
    
       new SetSection().designForm(this, mainPanel, "mini");
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        mainPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtLocationAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtlocationContactNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLocationDescription = new javax.swing.JTextArea();
        addbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtLocationContactPerson = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        closebtn = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        mainPanel.setBackground(new java.awt.Color(161, 214, 226));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Location:");
        mainPanel.add(jLabel3);
        jLabel3.setBounds(40, 70, 64, 17);

        txtLocationAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mainPanel.add(txtLocationAddress);
        txtLocationAddress.setBounds(40, 90, 330, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Contact Number:");
        mainPanel.add(jLabel4);
        jLabel4.setBounds(40, 150, 120, 17);

        txtlocationContactNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mainPanel.add(txtlocationContactNumber);
        txtlocationContactNumber.setBounds(40, 168, 330, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Contact Person:");
        mainPanel.add(jLabel5);
        jLabel5.setBounds(40, 230, 112, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Description:");
        mainPanel.add(jLabel6);
        jLabel6.setBounds(40, 300, 82, 17);

        txtLocationDescription.setColumns(20);
        txtLocationDescription.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtLocationDescription.setRows(5);
        jScrollPane1.setViewportView(txtLocationDescription);

        mainPanel.add(jScrollPane1);
        jScrollPane1.setBounds(40, 330, 330, 72);

        addbtn.setBackground(new java.awt.Color(0, 0, 102));
        addbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        mainPanel.add(addbtn);
        addbtn.setBounds(270, 430, 101, 40);

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        mainPanel.add(jButton2);
        jButton2.setBounds(40, 430, 101, 40);

        txtLocationContactPerson.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mainPanel.add(txtLocationContactPerson);
        txtLocationContactPerson.setBounds(40, 250, 330, 30);

        jPanel1.setBackground(new java.awt.Color(25, 149, 173));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/xbutton.png"))); // NOI18N
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        jPanel1.add(closebtn);
        closebtn.setBounds(370, 0, 40, 40);

        mainPanel.add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 40);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, 410, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
      
         
    }//GEN-LAST:event_addbtnActionPerformed

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_closebtnMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocationUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel closebtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtLocationAddress;
    private javax.swing.JTextField txtLocationContactPerson;
    private javax.swing.JTextArea txtLocationDescription;
    private javax.swing.JTextField txtlocationContactNumber;
    // End of variables declaration//GEN-END:variables

    

}
