/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Account.AccountPage;
import Sections.CreateSection;
import Sections.SetSection;
import Sections.StationSection;
import User.LeftCorner;
import User.NewUser;
import User.RightCorner;
import User.ViewUser;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Eunar B. Dayangco
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */

    private static Container currentPage;
    private static String currentDisplayPage;
    private static String currentDisplayCorner;
    private static Container adminAccount,viewUser,newUser;
    private static Container rightCorner,leftCorner;
   
    
    
    public MainPage() {
        initComponents();
        new SetSection().designForm(this, adminMainmainPanel, "mini");
        initContainer();
        designPanelButton();
    }
    
    public void initContainer(){
        
        //initializing the container
        adminAccount = new AccountPage().getContentPane();
        viewUser = new ViewUser().getContentPane();
        newUser = new NewUser().getContentPane();
        rightCorner = new RightCorner().getContentPane();
        leftCorner = new LeftCorner().getContentPane();
        
        containerSetSize(adminAccount);
        containerSetSize(viewUser);
        containerSetSize(newUser);
        
        /*rightCorner.removeAll();
        rightCorner.add(newUser);
        rightCorner.revalidate();
        rightCorner.repaint();*/
        currentDisplayPage = "newUser";
        currentDisplayCorner = "right";
        currentPage = rightCorner;
        
        
        //this is a button panel of newUser
         newUserPanel.setBackground(new Color(153,0,0));
         newUserPanel.setBorder(javax.swing.BorderFactory.createBevelBorder
                    (javax.swing.border.BevelBorder.LOWERED));
         newUserPanel.setEnabled(false);
         
         
          CreateSection.displayComponents(displayPanel, rightCorner);
          CreateSection.displayComponents(rightCorner, newUser);

    }
    public void containerSetSize(Container cont){
    
        cont.setSize(new Dimension(displayPanel.getWidth(),displayPanel.getHeight()));
    }
    public void setCornerLocation(){
    
         
           
           if(!addPage(leftCorner)){
            int accountPageXLocation = (int) leftCorner.getLocation().getX();
            int accountPageYLocation = (int) leftCorner.getLocation().getY();
                leftCorner.setLocation(accountPageXLocation+rightCorner.getWidth()
                        +(controlMenuPanel.getWidth()-80),accountPageYLocation);
                
           }
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminMainmainPanel = new javax.swing.JPanel();
        controlMenuPanel = new javax.swing.JPanel();
        accountPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newUserPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        minbtn = new javax.swing.JLabel();
        closebtn = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        adminMainmainPanel.setBackground(new java.awt.Color(102, 0, 0));
        adminMainmainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        controlMenuPanel.setBackground(new java.awt.Color(255, 204, 0));
        controlMenuPanel.setLayout(null);

        accountPanel.setBackground(new java.awt.Color(51, 0, 0));
        accountPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        accountPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accountPanelMousePressed(evt);
            }
        });
        accountPanel.setLayout(null);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MainComponents/account.png"))); // NOI18N
        accountPanel.add(jLabel3);
        jLabel3.setBounds(40, 10, 100, 80);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Account");
        accountPanel.add(jLabel4);
        jLabel4.setBounds(50, 90, 70, 14);

        controlMenuPanel.add(accountPanel);
        accountPanel.setBounds(30, 430, 180, 120);

        newUserPanel.setBackground(new java.awt.Color(51, 0, 0));
        newUserPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        newUserPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newUserPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newUserPanelMousePressed(evt);
            }
        });
        newUserPanel.setLayout(null);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MainComponents/new-user.png"))); // NOI18N
        newUserPanel.add(jLabel5);
        jLabel5.setBounds(40, 10, 100, 80);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("New User");
        newUserPanel.add(jLabel6);
        jLabel6.setBounds(50, 90, 70, 14);

        controlMenuPanel.add(newUserPanel);
        newUserPanel.setBounds(30, 90, 180, 120);

        searchPanel.setBackground(new java.awt.Color(51, 0, 0));
        searchPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        searchPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchPanelMousePressed(evt);
            }
        });
        searchPanel.setLayout(null);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MainComponents/Search.png"))); // NOI18N
        searchPanel.add(jLabel7);
        jLabel7.setBounds(40, 10, 100, 80);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Search");
        searchPanel.add(jLabel8);
        jLabel8.setBounds(50, 90, 70, 14);

        controlMenuPanel.add(searchPanel);
        searchPanel.setBounds(30, 260, 180, 120);

        logoutbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutbtn.setText("LOG-OUT");
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
        });
        controlMenuPanel.add(logoutbtn);
        logoutbtn.setBounds(160, 10, 65, 17);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        minbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/LoginComponents/minimize.png"))); // NOI18N
        minbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minbtnMouseClicked(evt);
            }
        });
        jPanel1.add(minbtn);
        minbtn.setBounds(1010, 0, 28, 30);

        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/LoginComponents/cancel.png"))); // NOI18N
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        jPanel1.add(closebtn);
        closebtn.setBounds(1040, 0, 30, 30);

        displayPanel.setBackground(new java.awt.Color(102, 0, 0));
        displayPanel.setOpaque(false);

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 832, Short.MAX_VALUE)
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout adminMainmainPanelLayout = new javax.swing.GroupLayout(adminMainmainPanel);
        adminMainmainPanel.setLayout(adminMainmainPanelLayout);
        adminMainmainPanelLayout.setHorizontalGroup(
            adminMainmainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(adminMainmainPanelLayout.createSequentialGroup()
                .addComponent(controlMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        adminMainmainPanelLayout.setVerticalGroup(
            adminMainmainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminMainmainPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminMainmainPanelLayout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(controlMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(adminMainmainPanel);
        adminMainmainPanel.setBounds(0, 0, 1080, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       exitMessageDialog();
        
      
    }//GEN-LAST:event_formWindowClosed

    private void minbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minbtnMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minbtnMouseClicked

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
      exitMessageDialog();
    }//GEN-LAST:event_closebtnMouseClicked

    private void accountPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountPanelMousePressed
        setCornerLocation();
        
        if(!currentDisplayPage.equals("adminAccount")){
            
            if(currentDisplayCorner.equals("right")){
            
            CreateSection.displayComponents(leftCorner, adminAccount);
            currentDisplayCorner = "left";
            new SetSection().setDisplaytoBackward(leftCorner, 200, 70);
            new SetSection().setDisplaytoBackward(currentPage, 200, 70);
            currentPage = leftCorner;
            
        
            }else{
            CreateSection.displayComponents(rightCorner, adminAccount);
            currentDisplayCorner = "right";
            new SetSection().setDisplaytoForward(rightCorner, 200, 70);
            new SetSection().setDisplaytoForward(currentPage, 200, 70);
            currentPage = rightCorner;
        
            }
        
            currentDisplayPage = "adminAccount";
        
        }

       
       

    }//GEN-LAST:event_accountPanelMousePressed

    private void newUserPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserPanelMousePressed
        setCornerLocation();
        
        if(!currentDisplayPage.equals("newUser")){
            
            if(currentDisplayCorner.equals("right")){

                CreateSection.displayComponents(leftCorner, newUser);
                currentDisplayCorner = "left";
                new SetSection().setDisplaytoBackward(leftCorner, 200, 70);
                new SetSection().setDisplaytoBackward(currentPage, 200, 70);
                currentPage = leftCorner;


            }else{

                CreateSection.displayComponents(rightCorner, newUser);
                currentDisplayCorner = "right";
                new SetSection().setDisplaytoForward(rightCorner, 200, 70);
                new SetSection().setDisplaytoForward(currentPage, 200, 70);
                currentPage = rightCorner;

            }

            currentDisplayPage = "newUser";
        
        
        }
        

    
        
    }//GEN-LAST:event_newUserPanelMousePressed

    private void searchPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPanelMousePressed
       setCornerLocation();
       viewUser = new ViewUser().getContentPane();
       
       if(!currentDisplayPage.equals("viewUser")){
       
            if(currentDisplayCorner.equals("right")){

               CreateSection.displayComponents(leftCorner, viewUser);
               currentDisplayCorner = "left";
               new SetSection().setDisplaytoBackward(leftCorner, 200, 70);
               new SetSection().setDisplaytoBackward(currentPage, 200, 70);
               currentPage = leftCorner;
            
        
            }else{
            
                CreateSection.displayComponents(rightCorner, viewUser);
                currentDisplayCorner = "right";
                new SetSection().setDisplaytoForward(rightCorner, 200, 70);
                new SetSection().setDisplaytoForward(currentPage, 200, 70);
                currentPage = rightCorner;
        
            }
        
            currentDisplayPage = "viewUser";
       
       }
       

    }//GEN-LAST:event_searchPanelMousePressed

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked
       StationSection.setLoggedAdmin(null);
       this.setVisible(false);
       new Login.LoginUI().setVisible(true);
    }//GEN-LAST:event_logoutbtnMouseClicked

    private void newUserPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_newUserPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountPanel;
    private javax.swing.JPanel adminMainmainPanel;
    private javax.swing.JLabel closebtn;
    private javax.swing.JPanel controlMenuPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoutbtn;
    private javax.swing.JLabel minbtn;
    private javax.swing.JPanel newUserPanel;
    private javax.swing.JPanel searchPanel;
    // End of variables declaration//GEN-END:variables

 public boolean addPage(Container page){
     
     if(!displayPanel.isAncestorOf(page)){
        //CreateSection.displayInfoMessage("Ancestor?", "No");
        displayPanel.add(page);
        displayPanel.revalidate();
        displayPanel.repaint();
        
        return false;
     }
     else{
         //CreateSection.displayInfoMessage("Ancestor?", "Yes");
         return true;
     }
 
 }
 public void exitMessageDialog(){
      String message = "Are you sure you want to exit?";
        int reply = JOptionPane.showConfirmDialog(null, message, "Exit", JOptionPane.YES_NO_OPTION);
        
        if (reply == JOptionPane.YES_OPTION) {
           StationSection.setLoggedAdmin(null);
            this.setVisible(false);
            new Login.LoginUI().setVisible(true);
        }
 }
    public ArrayList<JPanel> otherPanels(JPanel panel){
       ArrayList<JPanel> panelbtns = new ArrayList <JPanel>(){};
       panelbtns.add(newUserPanel);
       panelbtns.add(accountPanel);
       panelbtns.add(searchPanel);
       panelbtns.remove(panel);
        
        return panelbtns;
    }
     public void designPanelButton(){
        Color colorIn = new Color(153,0,0);
        Color colorOut = new Color(51,0,0);
        
        setClickablePanel(accountPanel, colorIn, colorOut,otherPanels(accountPanel));
        setClickablePanel(searchPanel, colorIn, colorOut,otherPanels(searchPanel));
         setClickablePanel(newUserPanel, colorIn, colorOut,otherPanels(newUserPanel));
       
    }
   
     
      public void setClickablePanel(JPanel panel,Color colorEntered,Color colorExited,ArrayList <JPanel> otherPanels){
      
          panel.addMouseListener(new MouseListener() {
              @Override
              public void mouseClicked(MouseEvent e) {
                 
              }

              @Override
              public void mousePressed(MouseEvent e) {
                  

                  panel.setBorder(javax.swing.BorderFactory.createBevelBorder
                    (javax.swing.border.BevelBorder.LOWERED)); 
                    
                  for(JPanel panel:otherPanels){
                      
                    panel.setBorder(javax.swing.BorderFactory.
                          createLineBorder(Color.white));
                    panel.setBackground(colorExited);
                    panel = panel;
                  }

                  
              }

              @Override
              public void mouseReleased(MouseEvent e) {
                  
              }

              @Override
              public void mouseEntered(MouseEvent e) {
                  panel.setBackground(colorEntered);
                
                 
              }

              @Override
              public void mouseExited(MouseEvent e) {
                  
                  String borderClass = panel.getBorder().getClass().getSimpleName();
                
                  if(borderClass.equals("BevelBorder")){
                       panel.setBackground(colorEntered);
                  }else{
                    panel.setBackground(colorExited);
                  }
              }
          });
      }

}
