/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Main;

import Forms.PreviewForm;
import Views.Report.ReportPage;
import Views.Inventory.InventoryPage;
import Sections.CreateSection;
import Sections.SetSection;
import Views.Forms.FormPage;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Toolkit;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;


/**
 *
 * @author Eunar B. Dayangco
 */
public class DICTISMain extends javax.swing.JFrame {

   
    public Color setcolor;
    private static Container main,inventories,report,forms;
    
    
    public DICTISMain() {
        initComponents();
        init();
        this.setcolor = new Color(0,153,255);
        initContainer();
    }
    public void init(){
        
        this.setMinimumSize(new Dimension(bodyPanel.getWidth(),bodyPanel.getHeight()));
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, (dim.height/2-this.getSize().height/2)-30);
        new SetSection().setIcon(this);
        acct.setRenderer(new DefaultListCellRenderer() {
            public void paint(Graphics g) {
                setBackground(new Color(0,0,102));
                setForeground(Color.white);
                setBorder(new EmptyBorder(0, 0,0,0));
                super.paint(g);
            }
        });
        setImageMenuDisplay();
        // acct.setUI(new BasicComboBoxUI());
    
    }
    
    public void setImageMenuDisplay(){
        
        int width = 50;
        int height = 50;
        ClassLoader cl = this.getClass().getClassLoader();
       
        ImageIcon homeicon = new ImageIcon(cl.getResource("lib/home.png"));
        Image homeimg = homeicon.getImage() ;  
        Image homenewimg = homeimg.getScaledInstance( width, height,  java.awt.Image.SCALE_SMOOTH ) ;  
        homeicon = new ImageIcon( homenewimg );
        mainbtn.setIcon(homeicon);
        
        ImageIcon inventoryicon = new ImageIcon(cl.getResource("lib/inventories.png"));
        Image inventoryimg = inventoryicon.getImage() ;  
        Image inventorynewimg = inventoryimg.getScaledInstance( width, height,  java.awt.Image.SCALE_SMOOTH ) ;  
        inventoryicon = new ImageIcon( inventorynewimg );
        inventorybtn.setIcon(inventoryicon);
        
        ImageIcon reportsicon = new ImageIcon(cl.getResource("lib/reports.png"));
        Image reportsimg = reportsicon.getImage() ;  
        Image reportsnewimg = reportsimg.getScaledInstance( width, height,  java.awt.Image.SCALE_SMOOTH ) ;  
        reportsicon = new ImageIcon( reportsnewimg );
        reportbtn.setIcon(reportsicon);
        
        ImageIcon dashicon = new ImageIcon(cl.getResource("lib/dash.png"));
        Image dashimg = dashicon.getImage() ;  
        Image dashnewimg = dashimg.getScaledInstance( width, height,  java.awt.Image.SCALE_SMOOTH ) ;  
        dashicon = new ImageIcon( dashnewimg );
        formsbtn.setIcon(dashicon);
        
        UIManager.put("Button.margin", new Insets(2, 14, 2, 14));
       
    
    }
    public void initContainer(){
        main = new MainPage().getContentPane();
        inventories = new InventoryPage().getContentPane();
        report = new ReportPage().getContentPane();
      
        forms = new FormPage().getContentPane();
        CreateSection.displayComponents(platesPanel, main);
        setActiveColor(mainbtn,mainPanel,setcolor);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        acct = new javax.swing.JComboBox<>();
        mainPanel = new javax.swing.JPanel();
        mainbtn = new javax.swing.JButton();
        inventoriesPanel = new javax.swing.JPanel();
        inventorybtn = new javax.swing.JButton();
        reportsPanel = new javax.swing.JPanel();
        reportbtn = new javax.swing.JButton();
        FormsPanel = new javax.swing.JPanel();
        formsbtn = new javax.swing.JButton();
        platesPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        bodyPanel.setBackground(new java.awt.Color(0, 153, 255));
        bodyPanel.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/dictLogo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 30, 300, 130);

        acct.setBackground(new java.awt.Color(0, 0, 102));
        acct.setForeground(new java.awt.Color(255, 255, 255));
        acct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "View History", "View Account", "Logout" }));
        acct.setSelectedIndex(-1);
        acct.setToolTipText("");
        acct.setFocusable(false);
        acct.setLightWeightPopupEnabled(false);
        acct.setOpaque(false);
        acct.setRequestFocusEnabled(false);
        acct.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(acct);
        acct.setBounds(400, 30, 101, 24);

        mainPanel.setBackground(new java.awt.Color(0, 0, 102));
        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainPanelMouseClicked(evt);
            }
        });
        mainPanel.setLayout(null);

        mainbtn.setBackground(new java.awt.Color(0, 0, 102));
        mainbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mainbtn.setForeground(new java.awt.Color(255, 255, 255));
        mainbtn.setText("Main");
        mainbtn.setBorder(null);
        mainbtn.setFocusPainted(false);
        mainbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mainbtn.setIconTextGap(10);
        mainbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainbtnActionPerformed(evt);
            }
        });
        mainPanel.add(mainbtn);
        mainbtn.setBounds(50, 0, 230, 70);

        jPanel1.add(mainPanel);
        mainPanel.setBounds(0, 200, 330, 70);

        inventoriesPanel.setBackground(new java.awt.Color(0, 0, 102));
        inventoriesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoriesPanelMouseClicked(evt);
            }
        });
        inventoriesPanel.setLayout(null);

        inventorybtn.setBackground(new java.awt.Color(0, 0, 102));
        inventorybtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        inventorybtn.setForeground(new java.awt.Color(255, 255, 255));
        inventorybtn.setText("Inventories");
        inventorybtn.setBorder(null);
        inventorybtn.setFocusPainted(false);
        inventorybtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inventorybtn.setIconTextGap(10);
        inventorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventorybtnActionPerformed(evt);
            }
        });
        inventoriesPanel.add(inventorybtn);
        inventorybtn.setBounds(50, 0, 230, 70);

        jPanel1.add(inventoriesPanel);
        inventoriesPanel.setBounds(0, 280, 330, 70);

        reportsPanel.setBackground(new java.awt.Color(0, 0, 102));
        reportsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsPanelMouseClicked(evt);
            }
        });
        reportsPanel.setLayout(null);

        reportbtn.setBackground(new java.awt.Color(0, 0, 102));
        reportbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        reportbtn.setForeground(new java.awt.Color(255, 255, 255));
        reportbtn.setText("Reports");
        reportbtn.setBorder(null);
        reportbtn.setFocusPainted(false);
        reportbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reportbtn.setIconTextGap(10);
        reportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportbtnActionPerformed(evt);
            }
        });
        reportsPanel.add(reportbtn);
        reportbtn.setBounds(60, 0, 230, 70);

        jPanel1.add(reportsPanel);
        reportsPanel.setBounds(-10, 360, 340, 70);

        FormsPanel.setBackground(new java.awt.Color(0, 0, 102));
        FormsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FormsPanelMouseClicked(evt);
            }
        });
        FormsPanel.setLayout(null);

        formsbtn.setBackground(new java.awt.Color(0, 0, 102));
        formsbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        formsbtn.setForeground(new java.awt.Color(255, 255, 255));
        formsbtn.setText("Forms");
        formsbtn.setBorder(null);
        formsbtn.setFocusPainted(false);
        formsbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        formsbtn.setIconTextGap(10);
        formsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formsbtnActionPerformed(evt);
            }
        });
        FormsPanel.add(formsbtn);
        formsbtn.setBounds(50, 0, 230, 70);

        jPanel1.add(FormsPanel);
        FormsPanel.setBounds(0, 440, 330, 70);

        bodyPanel.add(jPanel1);
        jPanel1.setBounds(0, 0, 320, 670);

        platesPanel.setBackground(new java.awt.Color(0, 153, 255));
        platesPanel.setLayout(null);
        bodyPanel.add(platesPanel);
        platesPanel.setBounds(320, 0, 970, 670);

        getContentPane().add(bodyPanel);
        bodyPanel.setBounds(0, 0, 1290, 670);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mainbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainbtnActionPerformed
        resetMenuColor();
        setActiveColor(mainbtn, mainPanel,  this.setcolor);
        CreateSection.displayComponents(platesPanel, main);
    }//GEN-LAST:event_mainbtnActionPerformed

    private void inventorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventorybtnActionPerformed
        resetMenuColor();
        setActiveColor(inventorybtn, inventoriesPanel,  this.setcolor);
        CreateSection.displayComponents(platesPanel, inventories);
    }//GEN-LAST:event_inventorybtnActionPerformed

    private void reportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportbtnActionPerformed
        resetMenuColor();
        setActiveColor(reportbtn, reportsPanel,  this.setcolor);
         CreateSection.displayComponents(platesPanel, report);
    }//GEN-LAST:event_reportbtnActionPerformed

    private void formsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formsbtnActionPerformed
            
        resetMenuColor();
        setActiveColor(formsbtn, FormsPanel,  this.setcolor);
        CreateSection.displayComponents(platesPanel, forms);
        
        
    }//GEN-LAST:event_formsbtnActionPerformed

    private void mainPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseClicked
        
        resetMenuColor();
        setActiveColor(mainbtn, mainPanel, this.setcolor);
        CreateSection.displayComponents(platesPanel, main);
    }//GEN-LAST:event_mainPanelMouseClicked

    private void inventoriesPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoriesPanelMouseClicked
        
        resetMenuColor();
        setActiveColor(inventorybtn, inventoriesPanel,  this.setcolor);
        CreateSection.displayComponents(platesPanel, inventories);
    }//GEN-LAST:event_inventoriesPanelMouseClicked

    private void reportsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsPanelMouseClicked
        
        resetMenuColor();
        setActiveColor(reportbtn, reportsPanel, this.setcolor);
         CreateSection.displayComponents(platesPanel, report);
    }//GEN-LAST:event_reportsPanelMouseClicked

    private void FormsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FormsPanelMouseClicked
        resetMenuColor();
        setActiveColor(formsbtn, FormsPanel,  this.setcolor);
        CreateSection.displayComponents(platesPanel, forms);
    }//GEN-LAST:event_FormsPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DICTISMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DICTISMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DICTISMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DICTISMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DICTISMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FormsPanel;
    private javax.swing.JComboBox<String> acct;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton formsbtn;
    private javax.swing.JPanel inventoriesPanel;
    private javax.swing.JButton inventorybtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton mainbtn;
    private javax.swing.JPanel platesPanel;
    private javax.swing.JButton reportbtn;
    private javax.swing.JPanel reportsPanel;
    // End of variables declaration//GEN-END:variables

     public void resetMenuColor(){
         
        mainbtn.setBackground(new Color(0,0,102));
        inventorybtn.setBackground(new Color(0,0,102));
        reportbtn.setBackground(new Color(0,0,102));
        formsbtn.setBackground(new Color(0,0,102));
        
        mainPanel.setBackground(new Color(0,0,102));
        inventoriesPanel.setBackground(new Color(0,0,102));
        reportsPanel.setBackground(new Color(0,0,102));
        FormsPanel.setBackground(new Color(0,0,102));
        
        mainbtn.setForeground(new Color(255,255,255));
        inventorybtn.setForeground(new Color(255,255,255));
        reportbtn.setForeground(new Color(255,255,255));
        formsbtn.setForeground(new Color(255,255,255));
        
    }
     
      public void setActiveColor(JButton button,JPanel panel,Color color){
        //Main - 0,153,255
      
        button.setBackground(color);
        button.setForeground(Color.BLACK);
        panel.setBackground(color);
        
    }


}
