/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sticker;

import Database.InventoryDB;
import Model.Inventory;
import Sections.TransitionSection;
import Sections.CreateSection;
import Sections.SetSection;
import java.awt.Color;
import java.awt.Component;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eunar B. Dayangco
 */
public class CreateSticker extends javax.swing.JFrame {

    /**
     * Creates new form CreateSticker
     */
   
    
    public CreateSticker() {
        initComponents();
      
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stickerbodyPanel = new javax.swing.JPanel();
        headbar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        minbtn = new javax.swing.JLabel();
        closebtn = new javax.swing.JLabel();
        categoryList = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        resultTableScrollPane = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        printScrollPane = new javax.swing.JScrollPane();
        printListItem = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        addtoPrintList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        stickerbodyPanel.setBackground(new java.awt.Color(51, 255, 0));
        stickerbodyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        stickerbodyPanel.setToolTipText("");
        stickerbodyPanel.setLayout(null);

        headbar.setBackground(new java.awt.Color(0, 0, 0));
        headbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));
        headbar.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CREATE STICKER");
        headbar.add(jLabel3);
        jLabel3.setBounds(10, -6, 140, 40);

        minbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/headers/minimize.png"))); // NOI18N
        minbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minbtnMouseClicked(evt);
            }
        });
        headbar.add(minbtn);
        minbtn.setBounds(660, 0, 30, 30);

        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/headers/cancel.png"))); // NOI18N
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        headbar.add(closebtn);
        closebtn.setBounds(690, 0, 30, 30);

        stickerbodyPanel.add(headbar);
        headbar.setBounds(0, 0, 720, 30);

        categoryList.setBackground(new java.awt.Color(51, 255, 0));
        categoryList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        categoryList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name", "Par No", "Location" }));
        categoryList.setFocusable(false);
        categoryList.setOpaque(false);
        stickerbodyPanel.add(categoryList);
        categoryList.setBounds(50, 70, 130, 40);

        jTextField1.setBackground(new java.awt.Color(51, 153, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        stickerbodyPanel.add(jTextField1);
        jTextField1.setBounds(190, 70, 310, 40);

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("FIND");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setFocusPainted(false);
        stickerbodyPanel.add(jButton1);
        jButton1.setBounds(520, 70, 160, 40);

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Show Info");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setFocusPainted(false);
        stickerbodyPanel.add(jButton2);
        jButton2.setBounds(50, 350, 160, 40);

        resultTableScrollPane.setOpaque(false);

        resultTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PAR No", "Name", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        resultTable.setOpaque(false);
        resultTableScrollPane.setViewportView(resultTable);

        stickerbodyPanel.add(resultTableScrollPane);
        resultTableScrollPane.setBounds(50, 120, 452, 220);

        printScrollPane.setBackground(new java.awt.Color(51, 255, 0));
        printScrollPane.setOpaque(false);

        printListItem.setBackground(new java.awt.Color(51, 255, 0));
        printListItem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        printListItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        printListItem.setOpaque(false);
        printScrollPane.setViewportView(printListItem);

        stickerbodyPanel.add(printScrollPane);
        printScrollPane.setBounds(520, 120, 160, 220);

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("PRINT");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setFocusPainted(false);
        stickerbodyPanel.add(jButton3);
        jButton3.setBounds(520, 350, 160, 40);

        addtoPrintList.setBackground(new java.awt.Color(0, 0, 102));
        addtoPrintList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addtoPrintList.setForeground(new java.awt.Color(255, 255, 255));
        addtoPrintList.setText("Add to Print List");
        addtoPrintList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addtoPrintList.setFocusPainted(false);
        addtoPrintList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtoPrintListActionPerformed(evt);
            }
        });
        stickerbodyPanel.add(addtoPrintList);
        addtoPrintList.setBounds(320, 350, 180, 40);

        getContentPane().add(stickerbodyPanel);
        stickerbodyPanel.setBounds(0, 0, 720, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minbtnMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minbtnMouseClicked

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        new TransitionSection().fromBottom_toTop(this, 70);
       
    }//GEN-LAST:event_closebtnMouseClicked

    private void addtoPrintListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtoPrintListActionPerformed
 


        
    }//GEN-LAST:event_addtoPrintListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateSticker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateSticker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateSticker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateSticker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateSticker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtoPrintList;
    private javax.swing.JComboBox<String> categoryList;
    private javax.swing.JLabel closebtn;
    private javax.swing.JPanel headbar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel minbtn;
    private javax.swing.JList<String> printListItem;
    private javax.swing.JScrollPane printScrollPane;
    private javax.swing.JTable resultTable;
    private javax.swing.JScrollPane resultTableScrollPane;
    private javax.swing.JPanel stickerbodyPanel;
    // End of variables declaration//GEN-END:variables

    
}
